package de.mpii.microblogtrack.component.filter;

import org.apache.log4j.Logger;
import twitter4j.JSONObject;
import twitter4j.Status;

/**
 * filter out all non-English tweet based on twitter API's lang field
 *
 * @author khui
 */
public class LangFilterTW implements Filter {

    final Logger logger = Logger.getLogger(LangFilterTW.class);

    /**
     * the input is generated by StatusFilter
     *
     * @param msg
     * @param json
     * @param status
     * @return
     */
    @Override
    public boolean isRetain(String msg, JSONObject json, Status status) {
        boolean isen = false;
        String langcode = status.getLang();
        if (langcode != null) {
            if (langcode.equals("en")) {
                isen = true;
            }
        }
        return isen;
    }

    public String langdetect(String msg, JSONObject json, Status status) {
        return status.getLang();
    }

}
