package de.mpii.microblogtrack.filter;

import org.apache.log4j.Logger;
import twitter4j.JSONObject;
import twitter4j.Status;

/**
 * filter out all non-English tweet
 *
 * @author khui
 */
public class LangFilter implements Filter {

    final Logger logger = Logger.getLogger(LangFilter.class);

    private String rawMsg;

    private JSONObject json = null;

    private Status status = null;

    private long tweetid = -1;

    /**
     * the input is generated by StatusFilter
     *
     * @param msg
     * @param json
     * @param status
     * @return
     */
    @Override
    public boolean isRetain(String msg, JSONObject json, Status status) {
        this.rawMsg = msg;
        this.json = json;
        this.status = status;
        this.tweetid = status.getId();
        boolean isen = false;
        String langcode = status.getLang();
        if (langcode != null) {
            if (langcode.equals("en")) {
                isen = true;
            }
        }
        return isen;
    }

}
